name: Run All Crawlers
on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Are you sure?'     
        required: true
        default: 'yes'
jobs:
  run_all_crawlers:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      GOOGLE_MAP_API_KEY:  ${{ secrets.GOOGLE_MAP_API_KEY }}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - run: |
        yarn install
        cd server
        yarn build
    - run: node server/dist/crawlers/segaCrawler.js
    - run: node server/dist/crawlers/taikoCrawler.js
    - run: node server/dist/crawlers/bemaniCrawler.js
    - run: node server/dist/crawlers/popnCrawler.js
      